name: Ubuntu Latest build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Manually enable/disable this long test
    # Write an if statement that is always false
    if: true
    steps:
      - uses: actions/checkout@v3
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install gfortran
        run: sudo apt-get install gfortran
      - name: Install ghostscript
        run: sudo apt-get install ghostscript
      - name: make VaST
        run: make
      - name: prepare for the test
        run: echo "1" > ../THIS_IS_HPCC 
      - name: test VaST
        run: util/examples/test_vast.sh
