name: FreeBSD build

on: [push]

jobs:
  test:
    runs-on: macos-12
    env:
      # Example of how tokens are propagated to the VM
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v3
    - name: Check commit message
      id: check_commit
      run: |
        commit_message=$(git log --format=%B -n 1 ${{ github.event.after }})
        if [[ "${commit_message}" == *"notest"* ]]; then
          echo "Commit contains 'notest'. Skipping tests."
          echo "SKIP=true" >> $GITHUB_ENV
        else
          echo "SKIP=false" >> $GITHUB_ENV
        fi
    - name: Test in FreeBSD
      id: test
      if: env.SKIP != 'true'
      uses: vmactions/freebsd-vm@v0
      with:
        # Example of how tokens are propagated to the VM
        envs: 'MYTOKEN MYTOKEN2'
        # Use sh shell
        usesh: true
        # When using rsync, you can define copyback: false to not copy files back from the VM in to the host.
        copyback: false
        prepare: |
          pkg install -y bash gcc gmake libx11 curl wget pgplot 

        run: |
          make
