name: Ubuntu 22.04 build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Update apt-get
      run: sudo apt-get update
    - name: Fix
      run: sudo apt-get install -f
    - name: Install gfortran
      run: sudo apt-get install gfortran
    - name: Install ghostscript
      run: sudo apt-get install ghostscript
    - name: Install shellcheck
      run: sudo apt-get install shellcheck
    - name: make VaST
      run: make
    - name: Shellcheck VaST BASH scripts lib
      run: for i in lib/*sh ;do shellcheck --severity=error  $i ;done
    - name: Shellcheck VaST BASH scripts util
      run: for i in util/*sh ;do shellcheck --severity=error  $i ;done
    - name: Shellcheck VaST BASH scripts util/transients
      run: for i in util/transients/*sh ;do shellcheck --severity=error  $i ;done
    - name: Shellcheck VaST BASH scripts util/examples
      run: for i in util/examples/*sh ;do shellcheck --severity=error  $i ;done
