name: macOS 11 MacPorts build

on: [push]

jobs:
  build:

    runs-on: macos-11

    # Manually enable/disable this test
    # Write an if statement that is always true/false
    if: true
    steps:
    - uses: actions/checkout@v3
    - name: Install MacPorts
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        source ./macports-ci install
    - name: port upgrade outdated
      run: sudo port upgrade outdated
    - name: Install gcc, g++, gfortran, and wget
      run: sudo port install gcc12 wget
    - name: Install X11 header files
      run: sudo port install xorg-libX11
    - name: Install libpng
      run: sudo port install libpng
    - name: make VaST
      run: make
