name: FreeBSD build

on: [push]

jobs:
  test:
    runs-on: macos-12
    env:
      # Example of how tokens are propagated to the VM
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v3
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        # Example of how tokens are propagated to the VM
        envs: 'MYTOKEN MYTOKEN2'
        # Use sh shell
        usesh: true
        # When using rsync, you can define copyback: false to not copy files back from the VM in to the host.
        copyback: false
        prepare: |
          pkg install -y bash gcc gmake libx11 curl wget pgplot 

        run: |
          make
