name: Ubuntu build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Manually enable/disable this long test
    # Write an if statement that is always true/false
    if: true
    steps:
      - uses: actions/checkout@v3
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install gfortran
        run: sudo apt-get install gfortran
      - name: Install ghostscript
        run: sudo apt-get install ghostscript
      - name: Install shellcheck
        run: sudo apt-get install shellcheck
      - name: make VaST
        run: make
      - name: Syntax-check the test script
        run: bash -n util/examples/test_vast.sh
      - name: Syntax-check the NMW transient search script
        run: bash -n util/transients/transient_factory_test31.sh
      - name: Prepare for the test
        run: echo "1" > ../THIS_IS_HPCC 
      - name: Test VaST
        run: util/examples/test_vast.sh
