name: Ubuntu 18.04 C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Fix ubuntu repository URLs
      run: sudo sed -i.bak -r 's/(archive|security).ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install gfortran
      run: sudo apt-get install gfortran
    - name: Install ghostscript
      run: sudo apt-get install ghostscript
    - name: make VaST
      run: make
