name: Ubuntu 18.04 C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Update apt-get
      run: sudo apt-get update
    - name: Fix
      run: sudo apt-get install -f
    - name: Install gfortran
      run: sudo apt-get install gfortran
    - name: Install ghostscript
      run: sudo apt-get install ghostscript
    - name: make VaST
      run: make
